### ISSUE TITLE
base.html中好像有问题

### ISSUE THREAD

**Issue by goodbad3** [greyli/catchat#1]
-     <script type="text/javascript">
        var root_url = "{{ url_for('chat.home') }}";
        var messages_url = "{{ url_for('chat.get_messages') }}";
        var current_user_id = {{ current_user.id|default(0) }};
        var csrf_token = "{{ csrf_token() }}";
    </script>

var current_user_id = {{ current_user.id|default(0) }};这个？？？？？

**Comment by greyli** [comment]
具体说说？

**Comment by goodbad3** [comment]
用sublime打开是红色的，
var current_user_id = {{ current_user.id|default(0) }}
最后一个    }   是红色的

**Comment by greyli** [comment]
编辑器的提示有时候是可以忽略的。这里是把 Jinja 写到了 JavaScript 里，编辑器只会把这一段代码看做 JavaScript 去解析，所以提示语法错误，渲染后的 HTML 会是正确的。
