### ISSUE TITLE
代码高亮那块

### ISSUE THREAD

**Issue by goodbad3** [greyli/catchat#3]
<span></span>def hello():
    return "Hello World"
总有个<span></span>，还有tab键不能用

**Comment by goodbad3** [comment]
Locking [packages] dependencies…
Locking Failed!
[pipenv.exceptions.ResolutionFailure]:   File "d:/python36/lib/site-packages/pipenv/resolver.py", line 69, in resolve
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "d:\python36\lib\site-packages\pipenv\utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "d:\python36\lib\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "d:\python36\lib\site-packages\pipenv\utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches pyments
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches pyments
No versions found
Was https://pypi.tuna.tsinghua.edu.cn/simple/ reachable?
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "d:\python36\lib\site-packages\pipenv\utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "d:\python36\lib\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "d:\python36\lib\site-packages\pipenv\utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches pyments
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches pyments
No versions found
Was https://pypi.tuna.tsinghua.edu.cn/simple/ reachable?

**Comment by goodbad3** [comment]
出现<span></span><span class="k">def</span> <span class="nf">hello</span><span class="p">():</span>
    <span class="k">return</span> <span class="s2">"Hello World"</span>

**Comment by goodbad3** [comment]
<span></span><span class="k">def</span> <span class="nf">hello</span><span class="p">():</span>
    <span class="k">return</span> <span class="s2">"Hello World"</span>

**Comment by greyli** [comment]
书里的拼写错了，应该是：
```bash
$ pipenv install pygments
```

**Comment by greyli** [comment]
用空格代替 Tab。

**Comment by goodbad3** [comment]
好的，先试试

**Comment by goodbad3** [comment]
还是不行啊，

**Comment by goodbad3** [comment]
‘’‘<span></span><span class="k">def</span> <span class="nf">hello</span><span class="p">():</span>
    <span class="k">return</span> <span class="s2">"Hello World"</span>’‘’，出现这

**Comment by goodbad3** [comment]
可以了，bleach版本不对，谢谢作者
