### ISSUE TITLE
The /messages page is not styled.

### ISSUE THREAD

**Issue by wangtianxing1010** [greyli/catchat#8]
The template being used for /messages page is '_messages.html', which is used as a sub-template in 'home.html' to render a list of messages. However, when used alone on /messages page, no style will be applied.

**Comment by greyli** [comment]
Hi, thanks for reporting on this (and the PR)! Basically, `/messages` is a hidden endpoint, in other words, it's just designed for internal use.

**Comment by wangtianxing1010** [comment]
Hi Grey,
Thanks for your reply! I figured it too and therefore I closed the PR.

Thank you for your great tutorial.

Would you be able to take a look at the Twitter oauth part of the code too?
It doesn't seem to work anymore. I posted a question in the forum, here is
the link: https://discuss.helloflask.com/t/topic/371

Thank you very much!

Grey Li <notifications@github.com> 于 2019年10月15日周二 下午8:58写道：
